<?php
$order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);

?>
<h2><?php echo $this->__('Demo Payment Gateway') ?></h2>
<p>It's a demo page acting as a payment gateway interface! So don't worry you won't get charged :-)</p>
<form name="custompaymentmethod" method="post" action="<?php echo Mage::helper('sp_custompayment')->getPaymentGatewayUrl(); ?>">
    <input type="hidden" name="orderId" value="<?php echo $orderId; ?>">
    <div>
        <label>Test error order page</label>
        <input type="checkbox" name="error" value="0">
    </div>
    <input type="submit" value="<?php echo $this->__('Make Payment') ?>" />
</form>